version: "3"

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - tcprouter
  tcprouter:
    build: 
      context: .
      dockerfile: Dockerfile.tcprouter
    ports:
      - "1337:1337"
